### ISSUE TITLE
这个主题的一些问题反馈

### ISSUE THREAD

**Issue by qinyuanpei** [DaiXiang/hexo-theme-BsLight#1]
1、extra文件夹里有许多东西都没有用到，我觉得有用的只有toc和totop这两个功能。可是奇怪的是这个totop的图片居然找不到，img下面的那个图片如果加上的话就会出现两个按钮。
2、增加了顶部的标题栏后，文章会有一部分被遮住，这个问题我自己在主题中修正了。
3、侧栏Weight的title背景的高度可以调整吗？和顶部一样感觉没有层次感。
4、footer其实可以做更多的尝试，我正在向着pacman的方向改进，版权说明在左、图标在右。还有我看到好多主题里里面像社交网站的图标都不是用图片做的，如果这一点能改进就好了，这样可以加快本地生成
5、删除了好多国外的CDN，换成本地的，这样在本地调试的时候会好些，不过会影响速度

**Comment by DaiXiang** [comment]
1. 所有文件对应相应的功能，无多余；toTop 图标不是使用的图片实现
2. 顶部标题栏被遮住是由于 js 加载不完全导致

**Comment by qinyuanpei** [comment]
哦，原来如此，多谢！对了,你有没有想过给这个主题写一个archives的widget啊，貌似Light主题里面就没有这个吧

**Comment by DaiXiang** [comment]
不会，这个主题不会怎么更新了。不过我印象中好像有这个的
